#predicted target column
target_column: repeat_buyer

#fraction of data used for training
train_fraction: 0.7

#random seed to ensure train/test split is same every time
random_state: 42

#XGBoost hyperparameters
#Best Parameters: {'learning_rate': 0.2, 'n_estimators': 50}
model_params:
  n_estimators: 50 #no. of trees model will build
  learning_rate: 0.2
  random_state: 42 #random seed for model consistency