target_column: repeat_buyer

# Train/test split configuration (70% train / 30% test)
train_fraction: 0.7
random_state: 42

# Number of iterations for RandomizedSearchCV
n_iter: 20

# folds for cross-validation
cv: 5

# metric optimized (f1)
scoring: "f1"

# File to save/load best params
best_params_path: "conf/base/model_params/best_xgb_params.json"

threshold: 0.45